'''
Author: Michael Gogins

This module translates MIDI files generated by musx to standard Csound scores
where each note is an "i" statement in the format:
```
i instrument_number time_seconds duration_seconds midi_key midi_velocity
```
'''
import math
from .note import Note
from .seq import Seq
from musx.midi import MidiFile

'''
Translates the MIDI event into a Csound "i" statement.
'''
def to_i_statement(channel, time_, duration, midi_key, midi_velocity):
    i_statement = "i {} {} {} {} {}".format(1 + channel, time_, duration, midi_key, midi_velocity)
    return i_statement
    
'''
Returns a Csound score file as a single string, translated from the MIDI file.
It is assumed that times are in seconds.
'''
def to_csound_score(midifile):
    csound_score = []
    for track in midifile:
        for event in track:
            print(type(event), event)
            if isinstance(event, Note) == True:
                i_statement = to_i_statement(event.instrument, event.time, event.duration, event.pitch, event.amplitude)
                csound_score.append(i_statement + "\n")
    return ''.join(csound_score)
    


